---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  labels:
    app: "srvDocumento"
    provider: "fabric8"
    version: "0.0.1-SNAPSHOT"
    group: "co.com.invima.maestro"
  name: "srvdocumento"
data:
  co.com.invima.procedureonline.echovalue: "teestvalue1"
  SQL_URL: "jdbc:sqlserver://192.168.1.35;database=Maestra"
  SQL_USERNAME: "Invima"
  SQL_PASSWORD: "Admin2021"
  SQL_SCHEMA: "dbo"
